version: "3.9"
networks:
  docker_test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
services:
  vertica:
    image: "glarik/vertica:10.0.0-RHEL7"
    command: ssh -fNT -L 50010:localhost:50010 root@10.5.0.6 -o PreferredAuthentications=password
    ports:
      - "5433:5433"
    volumes:
      - ./vertica-hdfs-config/hadoop:/etc/hadoop/conf
    networks:
      docker_test:
        ipv4_address: 10.5.0.5
    depends_on:
      - hdfs
  hdfs:
    image: "mdouchement/hdfs"
    ports:
      - "22022:22"
      - "8020:8020"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
    stdin_open: true
    networks:
      docker_test:
        ipv4_address: 10.5.0.6
