version: "3.9"
services:
  krbclient:
    build: ./client-krb
    networks:
      - "example"
    domainname: "example.com"
    volumes:
      - "./..:/spark-connector"
      - "./client-krb:/client-krb"
      - "./vertica-hdfs-config/hadoop-kerberized:/etc/hadoop/conf"
    stdin_open: true
    env_file:
      - "krb.env"
    ports:
      - "5050:5050"
  kdc:
    build: ./kdc
    container_name: "kdc"
    networks:
      - "example"
    hostname: "kdc"
    domainname: "example.com"
    env_file:
      - "krb.env"
    volumes:
      - "./kdc:/kdc"
      - "./keytabs:/keytabs"
    privileged: true
  vertica:
    image: "vertica/vertica-k8s"
    container_name: "vertica"
    networks:
      - "example"
    hostname: "vertica"
    domainname: "example.com"
    entrypoint: ["/bin/bash", "-c", "/opt/vertica/bin/docker-entrypoint.sh"]
    ports:
      - "5433:5433"
    volumes:
      - "./vertica-krb:/vertica-krb"
      - "./keytabs:/keytabs"
      - "./vertica-hdfs-config/hadoop-kerberized:/etc/hadoop/conf"
    env_file:
      - "krb.env"
    privileged: true
  hdfs:
    build: ./hdfs-krb
    container_name: "hdfs"
    networks:
      - "example"
    hostname: "hdfs"
    domainname: "example.com"
    ports:
      - "8020"
      - "8022"
      - "9870"
      - "9871"
      - "22"
    stdin_open: true
    tty: true
    volumes:
      - "./vertica-hdfs-config/hadoop-kerberized:/hadoop/conf"
      - "./hdfs-krb:/hdfs-krb"
      - "./keytabs:/keytabs"
    env_file:
      - "krb.env"
    privileged: true
    entrypoint: /bin/bash
  hdfs2:
    build: ./standby
    container_name: "hdfs2"
    networks:
      - "example"
    hostname: "hdfs2"
    domainname: "example.com"
    ports:
      - "8020"
      - "8022"
      - "9870"
      - "9871"
      - "22"
    stdin_open: true
    tty: true
    volumes:
      - "./vertica-hdfs-config/hadoop-kerberized:/hadoop/conf"
      - "./standby:/standby"
      - "./hdfs-krb:/hdfs-krb"
      - "./keytabs:/keytabs"
    env_file:
      - "krb.env"
    privileged: true
    entrypoint: /bin/bash
networks:
  example:
    name: "EXAMPLE.COM"
    driver: bridge
